name: Demo Docker Hub Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Connexion sécurisée à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Configuration du builder Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construction et envoi de l'image PHP-Apache
      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: ./php
          push: true
          # Remplacez "mon-pseudo/mon-app-php" par votre nom d'image
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-apache-crud:1

      # Test du Docker Compose (sans push les autres services)
      - name: Test Docker Compose launch
        run: docker-compose up -d --build
