services:
  nginx:
    image: nginx:alpine
    container_name: nginx_ssl_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - php-apache
    networks:
      - crud_network

  php-apache:
    build: ./php
    container_name: php_apache_crud
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - crud_network

  postgres:
    image: postgres:13
    container_name: postgres_crud
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crud_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crud_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_crud
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - crud_network

networks:
  crud_network:
    driver: bridge

volumes:
  db_data:
